name: zxing_lib
description: A Dart port of zxing that encode and decode multiple 1D/2D barcodes.
version: 0.7.0
homepage: https://www.shirne.com/
repository: https://github.com/shirne/zxing-dart
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  charset: ^1.0.1

dev_dependencies:
  test:
  fixnum: ^1.0.1
  lints: ^2.0.0
  image: ^3.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

