name: zxing_lib
description: A Dart port of zxing that encode and decode multiple 1D/2D barcodes.
version: 0.5.0
homepage: https://www.shirne.com/
repository: https://github.com/shirne/zxing-dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  convert: ^3.0.0
  charset: ^0.1.1

dev_dependencies:
  test:
  fixnum: ^1.0.0
  lints: ^1.0.1
  image: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

