name: zxing_lib
description: A Dart port of zxing that encode and decode multiple 1D/2D barcodes, Supported qrcode, pdf417, oned, maxicode, datamatrix, aztec.
version: 0.9.0
publish_to: 'none' # Prevent to publish to pub.dev

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  intl: ^0.17.0
  charset: ^1.1.1

dev_dependencies:
  test:
  fixnum: ^1.0.1
  lints: ^2.0.0
  image: ^3.1.3
  collection: ^1.16.0
