name: zxing_lib
description: A Dart port of zxing that encode and decode multiple 1D/2D barcodes, Supported qrcode, pdf417, oned, maxicode, datamatrix, aztec.
version: 1.1.2
publish_to: 'none' # Prevent to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <1.0.0"
  # Charset encoding/decoding (https://pub.dev/packages/charset)
  charset:
    git:
      url: https://github.com/llfbandit/charset-dart.git
      ref: 3ec2e497

dev_dependencies:
  test:
  fixnum: ^1.0.1
  lints:
  image: ^4.0.17
  collection:
